# Generated by Django 3.2 on 2021-04-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wackywidget',
            name='description',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
